import type { SectionType } from '@/types/sections'

export const SECTION_DEFAULTS: Record<SectionType, Record<string, unknown>> = {
  hero_banner: {
    image_url: '',
    headline: 'Welcome to our store',
    headline_size: 'large',
    subheadline: 'Discover our latest collection',
    cta_text: 'Shop Now',
    cta_url: '/products',
    cta_style: 'filled',
    second_cta_text: '',
    second_cta_url: '',
    height: 'large',
    content_position: 'center',
    overlay_opacity: 35,
    overlay_color: '#000000',
    text_color: '#ffffff',
  },
  hero_slideshow: {
    slides: [],
    autoplay: true,
    interval_ms: 5000,
    height: 'large',
  },
  hero_split: {
    image_url: '',
    headline: 'New collection',
    body: 'Crafted for everyday performance.',
    cta_text: 'Shop',
    cta_url: '/products',
    image_side: 'right',
  },
  hero_video: {
    video_url: '',
    poster_url: '',
    headline: '',
    autoplay: false,
    muted: true,
    height: 'large',
  },
  products_grid: {
    title: 'Our Products',
    show_title: true,
    title_align: 'left',
    source: 'all',
    category_id: null,
    tag: '',
    product_ids: [],
    columns_desktop: 4,
    columns_mobile: 2,
    products_count: 8,
    show_view_all: true,
    view_all_text: 'View All Products',
    view_all_url: '/products',
    card_style: 'default',
    show_rating: false,
  },
  products_carousel: {
    title: 'Featured',
    show_title: true,
    source: 'all',
    product_ids: [],
    products_count: 12,
    card_style: 'default',
  },
  product_featured: {
    product_id: null,
    show_gallery: true,
    show_price: true,
    layout: 'split',
  },
  categories_grid: {
    title: 'Shop by category',
    show_title: true,
    columns_desktop: 4,
    columns_mobile: 2,
    category_ids: [],
  },
  rich_text: {
    headline: 'About Us',
    body: 'Tell your brand story here...',
    align: 'center',
    cta_text: '',
    cta_url: '',
    max_width: '640px',
  },
  image_text: {
    image_url: '',
    image_alt: '',
    image_side: 'left',
    headline: '',
    body: '',
    cta_text: '',
    cta_url: '',
    image_ratio: 'landscape',
    gap: 'medium',
  },
  image_gallery: {
    images: [],
    layout: 'grid',
    columns_desktop: 3,
    gap: 'medium',
  },
  banner_full: {
    image_url: '',
    headline: '',
    subheadline: '',
    cta_text: '',
    cta_url: '',
    text_align: 'center',
    overlay_opacity: 40,
    height: 'medium',
  },
  banner_split: {
    image_url: '',
    headline: '',
    body: '',
    cta_text: '',
    cta_url: '',
    reverse: false,
  },
  countdown_timer: {
    headline: 'Sale ends soon',
    subheadline: '',
    end_date: '',
    bg_color: '#0F0F1A',
    text_color: '#FFFFFF',
    cta_text: '',
    cta_url: '',
  },
  testimonials: {
    title: 'What our customers say',
    layout: 'grid',
    columns: 3,
    style: 'card',
    items: [],
  },
  trust_badges: {
    items: [
      { icon: 'truck', label: 'Free Shipping', desc: 'On orders over EGP 500' },
      { icon: 'shield', label: 'Secure Payment', desc: 'SSL encrypted checkout' },
      { icon: 'arrow-uturn-left', label: 'Easy Returns', desc: 'Within 7 days' },
      { icon: 'chat', label: '24/7 Support', desc: 'We are here to help' },
    ],
    layout: 'row',
    style: 'icon-top',
  },
  logo_bar: {
    title: '',
    logos: [],
    grayscale: true,
  },
  faq_accordion: {
    title: 'FAQ',
    items: [],
  },
  newsletter_form: {
    headline: 'Subscribe',
    subheadline: 'Get updates and offers.',
    placeholder: 'Email address',
    button_text: 'Subscribe',
    bg_style: 'light',
  },
  contact_form: {
    headline: 'Contact us',
    subheadline: '',
    show_phone: true,
    submit_label: 'Send',
  },
  video_embed: {
    url: '',
    aspect_ratio: '16/9',
    title: '',
  },
  spacer: { height: 60, height_mobile: 40 },
  divider: { style: 'line', thickness: 1, color: '#E4E4EF', width: 'full' },
  custom_html: { html: '', css: '' },
}
